# -*- coding: utf-8 -*-
"""0404이진탐색.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syqq2UOSifqp5h06wcJmY0zzb2CFAaTC
"""

def binary_search(A,key,low,high):
  if(low<=high):
    mid=(low+high) // 2
    if key == A[mid]:
      return mid
    elif key < A[mid]:
      return binary_search(A,key,low,mid-1)

    else:
      return binary_search(A,key,mid+1,high)
  return -1

def binary_search_iter(A,key,low,high):
  while(low<=high):
    mid=(low+high)//2
    if key==A[mid]:
      return mid
    elif key>A[mid]:
      low=mid+1
    else:
      high=mid-1
  return -1

listA=[1,3,8,13,14,16,21,26,27,30,33,36,39,41,44,49]
print("입력리스트 ",listA)

print("33순환탐색 ",binary_search(listA,33,0,len(listA)-1))
print("33반복탐색 ",binary_search_iter(listA,33,0,len(listA)-1))
print("32순환탐색 ",binary_search(listA,32,0,len(listA)-1))
print("32반복탐색 ",binary_search_iter(listA,32,0,len(listA)-1))